### ISSUE TITLE
Typing Error in Importing Model User

### ISSUE THREAD

**Issue by morisha** [Khabz/travmeal#11]
In Models you have `models/user.js` but while you was importing, you referenced as `model/User`
https://github.com/Khabz/travmeal/blob/f4b68247523ab9f72fe36d7859b21a6cf0f17c29/server/routes/users.js#L3

More so in `middleware/auth.js` 
https://github.com/Khabz/travmeal/blob/f4b68247523ab9f72fe36d7859b21a6cf0f17c29/server/middleware/auth.js#L1

Recomended: Changing the name of the file to `User.js`

**Comment by Khabz** [comment]
Coolies. typo fixed
